FROM golang:1.22.1

WORKDIR /echofrontend

COPY . ./


RUN go mod download
RUN go build -C /echofrontend/severalinterceptorsplugin/ -buildmode=plugin  .
RUN go build -o /frontend ./frontend

EXPOSE 8080

CMD [ "/frontend" ]
