From golang:1.22.1

WORKDIR /echofrontend

COPY . ./


RUN go mod download
RUN go build -C /echofrontend/interceptors/ -buildmode=plugin .
RUN go build -o /frontend frontend.go

EXPOSE 8080

CMD [ "/frontend" ]
