From golang:1.22.1

WORKDIR /echoserver

COPY . ./


RUN go mod download
RUN go build -C /echoserver/interceptors/cache/ -buildmode=plugin .
RUN go build -o /frontend frontend.go

EXPOSE 8080

CMD [ "/frontend" ]
