FROM golang:1.22.1

WORKDIR /echoserver

COPY . ./


RUN go mod download
RUN go build -C /echoserver/severalinterceptorsplugin/ -buildmode=plugin .
RUN go build -o /server ./server

EXPOSE 9000

CMD ["/server"]